#!/usr/bin/env bash
set -euo pipefail

: "${AUTODL_PYTHON:?set AUTODL_PYTHON}"
: "${AUTODL_PROJECT_ROOT:?set AUTODL_PROJECT_ROOT}"
: "${BACE_COMRECGC_HANDOVER_REQUEST:?set BACE_COMRECGC_HANDOVER_REQUEST}"
: "${BACE_COMRECGC_CHECKPOINT_DIR:?set BACE_COMRECGC_CHECKPOINT_DIR}"
: "${BACE_COMRECGC_SOURCE_TRACE_ROOT:?set BACE_COMRECGC_SOURCE_TRACE_ROOT}"
: "${BACE_COMRECGC_SOURCE_RESOLVED_CONFIG:?set BACE_COMRECGC_SOURCE_RESOLVED_CONFIG}"
: "${BACE_DATASET_DIR:?set BACE_DATASET_DIR}"
: "${BACE_COMRECGC_CAP_OUTPUT_ROOT:?set BACE_COMRECGC_CAP_OUTPUT_ROOT}"
: "${BACE_GNN_CHECKPOINT:?set BACE_GNN_CHECKPOINT}"
: "${BACE_CALIBRATION_SPLIT:?set BACE_CALIBRATION_SPLIT}"
: "${BACE_TEST_SPLIT:?set BACE_TEST_SPLIT}"
: "${MOLCLR_ROOT:?set MOLCLR_ROOT}"
: "${MOLCLR_CHECKPOINT:?set MOLCLR_CHECKPOINT}"
: "${BACE_NEUROSED_CHECKPOINT:?set BACE_NEUROSED_CHECKPOINT}"
: "${COMRECGC_OFFICIAL_ROOT:?set COMRECGC_OFFICIAL_ROOT}"
: "${BACE_COMRECGC_SCIENCE_PID:?set BACE_COMRECGC_SCIENCE_PID}"
: "${BACE_COMRECGC_SCIENCE_START_TICKS:?set BACE_COMRECGC_SCIENCE_START_TICKS}"
: "${BACE_COMRECGC_SCIENCE_CMDLINE_SHA256:?set BACE_COMRECGC_SCIENCE_CMDLINE_SHA256}"
: "${BACE_COMRECGC_SCIENCE_CWD:?set BACE_COMRECGC_SCIENCE_CWD}"
: "${BACE_COMRECGC_SCIENCE_OUTPUT_ROOT:?set BACE_COMRECGC_SCIENCE_OUTPUT_ROOT}"
: "${BACE_COMRECGC_CONTROLLER_ID:?set BACE_COMRECGC_CONTROLLER_ID}"
: "${BACE_COMRECGC_CONTROLLER_RECEIPT:?set BACE_COMRECGC_CONTROLLER_RECEIPT}"
: "${BACE_COMRECGC_CONTROLLER_RECEIPT_SHA256:?set BACE_COMRECGC_CONTROLLER_RECEIPT_SHA256}"

[[ "${ALLOW_BACE_COMRECGC_20K_EXECUTOR:-0}" == "1" ]] || {
  echo "ALLOW_BACE_COMRECGC_20K_EXECUTOR=1 is required" >&2
  exit 64
}
[[ "${RUN_GNN_ABLATION:-0}" == "0" ]] || {
  echo "RUN_GNN_ABLATION must remain 0" >&2
  exit 64
}

cd "$AUTODL_PROJECT_ROOT"
export PYTHONPATH="$AUTODL_PROJECT_ROOT"
export PYTHONDONTWRITEBYTECODE=1
export PYTHONHASHSEED=0

exec "$AUTODL_PYTHON" \
  scripts/autodl/run_bace_comrecgc_resource_cap_executor.py \
  --config configs/hpc.yaml \
  run \
  --handover-request "$BACE_COMRECGC_HANDOVER_REQUEST" \
  --checkpoint-dir "$BACE_COMRECGC_CHECKPOINT_DIR" \
  --source-trace-root "$BACE_COMRECGC_SOURCE_TRACE_ROOT" \
  --source-resolved-config "$BACE_COMRECGC_SOURCE_RESOLVED_CONFIG" \
  --dataset-dir "$BACE_DATASET_DIR" \
  --output-root "$BACE_COMRECGC_CAP_OUTPUT_ROOT" \
  --python "$AUTODL_PYTHON" \
  --project-root "$AUTODL_PROJECT_ROOT" \
  --gnn-checkpoint "$BACE_GNN_CHECKPOINT" \
  --calibration-split "$BACE_CALIBRATION_SPLIT" \
  --test-split "$BACE_TEST_SPLIT" \
  --molclr-root "$MOLCLR_ROOT" \
  --molclr-checkpoint "$MOLCLR_CHECKPOINT" \
  --neurosed-checkpoint "$BACE_NEUROSED_CHECKPOINT" \
  --official-root "$COMRECGC_OFFICIAL_ROOT" \
  --science-pid "$BACE_COMRECGC_SCIENCE_PID" \
  --science-start-ticks "$BACE_COMRECGC_SCIENCE_START_TICKS" \
  --science-cmdline-sha256 "$BACE_COMRECGC_SCIENCE_CMDLINE_SHA256" \
  --science-cwd "$BACE_COMRECGC_SCIENCE_CWD" \
  --science-output-root "$BACE_COMRECGC_SCIENCE_OUTPUT_ROOT" \
  --controller-id "$BACE_COMRECGC_CONTROLLER_ID" \
  --controller-receipt "$BACE_COMRECGC_CONTROLLER_RECEIPT" \
  --controller-receipt-sha256 "$BACE_COMRECGC_CONTROLLER_RECEIPT_SHA256" \
  --poll-seconds "${SCHEDULER_POLL_SECONDS:-60}" \
  --exit-wait-seconds "${BACE_COMRECGC_EXIT_WAIT_SECONDS:-300}"
