#!/usr/bin/env python3
"""Audit teacher reliability and decoded PPO reward behavior without PPO updates."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from src.eval.reward_teacher_audit import (
    RewardTeacherAuditConfig,
    run_reward_teacher_audit,
)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--config",
        default=None,
        help="Optional config path for HPC wrapper parity. The audit uses explicit CLI paths.",
    )
    parser.add_argument(
        "--dataset-path",
        required=True,
        help="CSV/JSONL dataset containing parent_smiles and labels for teacher reliability audit.",
    )
    parser.add_argument(
        "--candidate-pool",
        required=True,
        help="Path to candidate_pool.jsonl generated by decoded PPO.",
    )
    parser.add_argument(
        "--teacher-path",
        required=True,
        help="Path to the teacher/oracle model bundle used for parent reliability audit.",
    )
    parser.add_argument(
        "--out-dir",
        required=True,
        help="Directory for JSON/TXT audit outputs.",
    )
    parser.add_argument(
        "--label-col",
        default="label",
        help="Preferred label column in the dataset CSV/JSONL. Falls back to common aliases if missing.",
    )
    parser.add_argument(
        "--smiles-col",
        default="parent_smiles",
        help="Preferred parent-smiles column in the dataset CSV/JSONL. Falls back to common aliases if missing.",
    )
    parser.add_argument(
        "--sim-sample-size",
        type=int,
        default=5000,
        help="Maximum sampled row count for optional correlation estimation. Use <=0 for full data.",
    )
    return parser


def main() -> None:
    args = build_parser().parse_args()
    summary = run_reward_teacher_audit(
        dataset_path=args.dataset_path,
        candidate_pool=args.candidate_pool,
        teacher_path=args.teacher_path,
        out_dir=args.out_dir,
        config=RewardTeacherAuditConfig(
            label_col=str(args.label_col),
            smiles_col=str(args.smiles_col),
            sim_sample_size=int(args.sim_sample_size),
        ),
    )
    final_judgment = summary["final_judgment"]
    print(f"dataset_path: {Path(args.dataset_path).expanduser().resolve()}")
    print(f"candidate_pool: {Path(args.candidate_pool).expanduser().resolve()}")
    print(f"teacher_path: {Path(args.teacher_path).expanduser().resolve()}")
    print(f"out_dir: {Path(args.out_dir).expanduser().resolve()}")
    print(f"teacher_reliable: {final_judgment['teacher_reliable']}")
    print(f"cf_reward_heavily_impacted: {final_judgment['cf_reward_heavily_impacted']}")
    print(
        f"reward_total_reasonably_cf_driven: {final_judgment['reward_total_reasonably_cf_driven']}"
    )
    print(f"possible_projection_loophole: {final_judgment['possible_projection_loophole']}")
    print(f"possible_size_loophole: {final_judgment['possible_size_loophole']}")
    print(f"primary_diagnosis: {final_judgment['primary_diagnosis']}")
    print(f"secondary_diagnosis: {final_judgment['secondary_diagnosis']}")


if __name__ == "__main__":
    main()
