#!/usr/bin/env python3
"""Audit a PPO candidate_pool.jsonl for selector-facing quality diagnostics."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from src.eval.candidate_pool_audit import AuditConfig, audit_candidate_pool, write_audit_outputs


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--config",
        default=None,
        help="Optional config path for HPC wrapper parity. The audit script does not read model config values.",
    )
    parser.add_argument(
        "--pool_jsonl",
        required=True,
        help="Path to candidate_pool.jsonl generated by decoded PPO.",
    )
    parser.add_argument(
        "--out_json",
        required=True,
        help="Path to write the machine-readable audit summary JSON.",
    )
    parser.add_argument(
        "--out_txt",
        required=True,
        help="Path to write the human-readable audit report.",
    )
    parser.add_argument(
        "--group_by_label",
        "--group-by-label",
        action="store_true",
        help="Also compute the major audit metrics separately for label=0 and label=1.",
    )
    parser.add_argument(
        "--sim_sample_size",
        "--sim-sample-size",
        type=int,
        default=5000,
        help="Maximum number of pairwise Tanimoto pairs to evaluate. Use <=0 for all pairs.",
    )
    parser.add_argument(
        "--topk_show",
        "--topk-show",
        type=int,
        default=10,
        help="How many top final fragments to show in the JSON/TXT outputs.",
    )
    return parser


def main() -> None:
    args = build_parser().parse_args()
    summary = audit_candidate_pool(
        args.pool_jsonl,
        config=AuditConfig(
            group_by_label=bool(args.group_by_label),
            sim_sample_size=int(args.sim_sample_size),
            topk_show=int(args.topk_show),
        ),
    )
    write_audit_outputs(
        summary,
        out_json=args.out_json,
        out_txt=args.out_txt,
    )
    print(f"pool_jsonl: {Path(args.pool_jsonl).expanduser().resolve()}")
    print(f"out_json: {Path(args.out_json).expanduser().resolve()}")
    print(f"out_txt: {Path(args.out_txt).expanduser().resolve()}")
    print(f"selector_ready: {summary['judgment']['recommend_start_selector']}")
    print(f"recommend_continue_long_ppo: {summary['judgment']['recommend_continue_long_ppo']}")
    print(f"recommend_sampling_tuning: {summary['judgment']['recommend_sampling_tuning']}")


if __name__ == "__main__":
    main()
